### PR TITLE
Remove distinction between browser and mobile builds

### PR DESCRIPTION
**Pull request by ptbrowne**
Draft: I've remarked this issue https://github.com/cozy/cozy-bar/pull/582/files that I think is important to take into account.

- Remove distinction between browser and mobile builds

Only 1 build is used. isMobileApp is used to differentiate between
mobile and browser platforms at runtime. More info in the commit.

This is a breaking change as cozy-bar.mobile.js is no longer shipped.

- Use flag to reduce activate redux logging of the bar

By default, the bar would attach a logger to redux. This pollutes the
app consoles that are seldom interested in what the bar is doing.
Here, with the flag, we can activate/deactivate logging easily.

### CODE REVIEW

**Comment by Crash--** [comment]
Est-ce que le fait d'avoir un seul bundle a changé la taille du bundle web par exemple ?

**Comment by ptbrowne** [comment]
Non, on avait pas de différence entre le code web et mobile puisqu'on utilise des checks au runtime depuis un moment.

**Comment by nono** [comment]
@ptbrowne do you know why the travis build is red?

**Comment by ptbrowne** [comment]
No, I do not plan to work on this further during the next 2 weeks.

**Comment by Crash--** [comment]
Is it still relevant @ptbrowne ?

**Comment by ptbrowne** [comment]
No :)

**Pull request closed without merging**
