### PR TITLE
Fix the cozy-bar

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by m4dz** [comment]
Doesn't it duplicates the `try...catch` matches block?

**Comment by nono** [comment]
@m4dz the selector was wrong in your code. And I don't have `document.matches` in firefox (and probably other browsers too, I didn't check). And if I use `element.matches`, it returns false, it does not throw an exception.

**Comment by m4dz** [comment]
Hmm, al'right, my bad, my code wa clearly wrong, I don't understand how I had tested it :cry:…

Doesn't throwing an exception a better way to handle the lack of given element ?

**Comment by nono** [comment]
> Doesn't throwing an exception a better way to handle the lack of given element ?

The important thing is to print a message in the console. An `if` or a `try / catch` is equally relevant and does the same.

**Comment by m4dz** [comment]
Al'right, let's do this. Thanks for te fix :+1:

**Pull request merged**
