### PR TITLE
[WIP] fix #30: Respect the name app on title :name_badge:

### LINKED ISSUE #30: Cozy Bar Title 🤔
After renaming Cozy Files to Cozy Drive, I see on the ['manifest.webapp'](https://github.com/cozy/cozy-drive/blob/master/manifest.webapp), the name have not Cozy word:

    "name": "Drive",

I change it to Cozy Drive but after this, when I start Cozy Drive app I see 'cozy cozy drive' on title.

I propose 2 changes:
- [ ] Remove the cozy word [here](https://github.com/cozy/cozy-bar/blob/cf3dbe758207e0a18535096a0de7e294b0bf6309/src/components/Bar.svelte#L9)
- [ ] Remove the lowercase [here](https://github.com/cozy/cozy-bar/blob/cf3dbe758207e0a18535096a0de7e294b0bf6309/src/styles/bar.css#L33)

What do you think ?

### PR DESCRIPTION
**Pull request by kosssi**
The changes I have tested to solve the issue #30, but its changes need to be validated by the engagement team

### CODE REVIEW

**Comment by CPatchane** [comment]
Agree, be careful about loosing the branding here.

**Comment by y-lohse** [comment]
Please also consider non-cozy apps that will use the bar, but have their own branding.

**Comment by CPatchane** [comment]
> Please also consider non-cozy apps that will use the bar, but have their own branding.

Right, some apps could use only an icon as app, but maybe it's too far here.

**Comment by kosssi** [comment]
it's solved by https://github.com/cozy/cozy-bar/pull/37 🖖

**Pull request closed without merging**
