### PR TITLE
chore: document cozy bar customization API

### PR DESCRIPTION
**Pull request by y-lohse**
[Actual preview here!](https://github.com/cozy/cozy-bar/blob/c0d08bf7796dfe79b328fbac8ab51760bbe5d775/README.md#customizing-the-content-of-the-bar)

### CODE REVIEW

**Comment by y-lohse** [comment]
[(2) 📱 Utiliser la nouvelle API de la cozy-bar pour piloter du contenu](https://trello.com/c/qDpTkLyf/598-2-%F0%9F%93%B1-utiliser-la-nouvelle-api-de-la-cozy-bar-pour-piloter-du-contenu)

**Comment by ptbrowne** [comment]
Your finding concerning the store is very interesting. I suggest we use a different `storeKey` in the cozy-bar to avoid this problem. https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by ptbrowne** [comment]
Otherwise, the doc is perfect, Kudos for the image ;)

**Comment by ptbrowne** [comment]
https://github.com/cozy/cozy-bar/issues/144

**Pull request merged**
