### PR TITLE
 fix: Don't subscribe to realtime if is public

### LINKED ISSUE #506: Cozybar on public page
Since we inject a CozyClient from the app to the bar, if we inject a non identified client (from a public view for instance) , we got an uncaught error : 
```
Uncaught Error: The application can't subscribe to io.cozy.apps
    at WebSocket.onSocketMessage (cozy-bar.js:17464)
```

This error is only blocking in our end to end test since every non catched error generate a real error. 

We currently fixed the error by removing the injection of cozyclient (tmp fix https://github.com/cozy/cozy-drive/pull/1530)

### PR DESCRIPTION
**Pull request by Crash--**
It's a try to fix #506 . I don't know if this is the way to go? Any ideas ?

### CODE REVIEW

**Comment by Crash--** [comment]
> Pas forcément fana du nom isPublic mais je n'ai rien de plus clair à proposer à chaud. Peut-être inPublicContext ou notAuthenticated ?

 
Oui je suis d'accord. Si on part sur ce genre de fix, je renommerai la variable un peu partout car elle fait partie de l'API existante déjà

**Comment by CPatchane** [comment]
D'accord aussi pour la renommer en `notAuthenticated` 👍

**Comment by ptbrowne** [comment]
In a public page, does not the cozyClient have a token ? I am trying to know if it would be possible to know if we are in a public page without explicitly telling so. I think cozyClient should be the one knowing this.

**Comment by Crash--** [comment]
CozyClient has a token and I just found out that it also has a `isLogged` attribute (https://github.com/cozy/cozy-client/blob/bbaa3db6f25d7f78aca7a1f51ca1b3d528217c59/packages/cozy-client/src/CozyClient.js#L74) 

But I don't know if I should change all the bar `isPublic` instances to `isLogged` since I don't know if this is the same behavior everywhere. Can we be logged on a public page?

**Comment by Crash--** [comment]
Quelques news de cette PR : 

- Quand on est en "stack-client", je me base sur "isLogged" du cozyclient, afin de ne pas souscrire au real time 
- Quand on est en "stack-internal", je continue de me baser sur le isPublic pour y souscrire

**Comment by nono** [comment]
Ping, can we merge this PR?

**Comment by CPatchane** [comment]
Thanks @Crash-- 👍

**Pull request merged**
