### PR TITLE
Append query string in AppLinker href prop 🚑

### PR DESCRIPTION
**Pull request by gregorylegarec**
App URLs with query string  were not properly encoded.

Let AppLinker manage the href with query string.

### CODE REVIEW

**Comment by ptbrowne** [comment]
Can we have a test for this please :) ?

**Comment by gregorylegarec** [comment]
@ptbrowne what would you test ?

**Comment by Crash--** [comment]
Testing a case like that: 

foo.bar/test/toto?fallback=https://fallback.fr/toto&from=test

**Comment by gregorylegarec** [comment]
@Crash-- To me this test should be in AppLinker test suite, as here we are just appending the querystring to a given url (and tests for that already exist).

**Comment by ptbrowne** [comment]
> @ptbrowne what would you test (I updated the snapshots) ?

I think http://fake.fr could have a query string, would it make the problem that we saw earlier more obvious ?

**Pull request merged**
